### ISSUE TITLE
Docker attestation generation fails

### ISSUE THREAD

**Issue by b-rowan** [UpstreamDataInc/goosebit#120]
Docker job fails on attestation generation, see job - https://github.com/UpstreamDataInc/goosebit/actions/runs/10710434164/job/29697391423

Might be unrelated, but trying to pull the image after this failed run results in the error
```
Error response from daemon: manifest for upstreamdata/goosebit:latest not found: manifest unknown: manifest unknown
```

**Comment by easybe** [comment]
Now the part that we didn’t/couldn‘t test is failing 😞

**Comment by b-rowan** [comment]
Don't worry about it lol, we can release a bunch of bug fix versions for now, just wanted to get versions out to test this stuff.
