### ISSUE TITLE
Docker build fails on `v0.2.3`

### ISSUE THREAD

**Issue by b-rowan** [UpstreamDataInc/goosebit#122]
See logs here - https://github.com/UpstreamDataInc/goosebit/actions/runs/10722320679/job/29733026032

Error is - 
```
 Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c addgroup -g 1000 goosebit &&     adduser -u 1000 -G goosebit -s /bin/sh -D goosebit &&     pip install --no-cache-dir         gunicorn         goosebit[postgresql]==$GOOSEBIT_VERSION" did not complete successfully: exit code: 1
 ```

**Comment by easybe** [comment]
Seems like a race condition. The first one failed because apparently the package was not available yet on PyPI. The re-run was able to upload the image, however, attestation failed again with the same error. We could either find out how that step really works or remove it for now.

In any case, the race condition is the tricky one...

**Comment by easybe** [comment]
BTW: The `master` Docker image tag should be deleted: https://hub.docker.com/layers/upstreamdata/goosebit/master/images/sha256-aee3d36c21f1b62483f4834a9783e8358c2f07c4cfde31f94ff1c63cd6300b1c?context=explore

**Comment by b-rowan** [comment]
> Seems like a race condition. The initial run failed because apparently, the package was not available yet on PyPI. The re-run was able to upload the image, however, attestation failed again with the same error. We could either find out how that step really works or remove it for now.
> 
> In any case, the race condition is the tricky one...

Hmmm...  Dumb solution, but we could just put like a sleep in there?  Other option is we actually query PyPI to check for firmware, I believe you can just run shell commands in actions, so just loop until the version we want shows up?

**Comment by b-rowan** [comment]
> BTW: The `master` Docker image tag should be deleted: https://hub.docker.com/layers/upstreamdata/goosebit/master/images/sha256-aee3d36c21f1b62483f4834a9783e8358c2f07c4cfde31f94ff1c63cd6300b1c?context=explore

Done.

**Comment by easybe** [comment]
> > Seems like a race condition. The initial run failed because apparently, the package was not available yet on PyPI. The re-run was able to upload the image, however, attestation failed again with the same error. We could either find out how that step really works or remove it for now.
> > In any case, the race condition is the tricky one...
> 
> Hmmm... Dumb solution, but we could just put like a sleep in there? Other option is we actually query PyPI to check for firmware, I believe you can just run shell commands in actions, so just loop until the version we want shows up?

Yes, I am considering polling. But, will think about it some more.
