### ISSUE TITLE
Not all software entries are listed in "Update Mode" dropdown

### ISSUE THREAD

**Issue by easybe** [UpstreamDataInc/goosebit#136]
When configuring a device, only a few software entries can be selected when there are a lot of entries in the DB (resulting in paging). The same goes for the "Software" dropdown in the rollout creation dialog.

We have to come up with a solution that scales. Perhaps add a filter/search field?

In the meantime, simply showing the newest entries would help.

**Comment by b-rowan** [comment]
I think we can just apply a smaller version of the software datatable in the modal and use that for selection, since we already scale that pretty well (to my understanding).
