### ISSUE TITLE
Online status ("Up") flickering 

### ISSUE THREAD

**Issue by easybe** [UpstreamDataInc/goosebit#137]
At least with our deployment, even though my device is obviously communicating with the server (as indicated by "Last seen") the "Up" status turns red from time to time.

**Comment by b-rowan** [comment]
The `up` value just  checks if the device has communicated within whatever value is set for poll time on that device.  We could change it to  check against default poll time, plus a couple of seconds.

**Comment by easybe** [comment]
I think there should be quite a margin, maybe in percent? Eventually, we plan to use a poll time of 1 day or more, so we should keep that in mind.

**Comment by b-rowan** [comment]
I think anywhere from 1.2 - 1.5X the poll time would be fine.  We could also make that configurable pretty easily, just add it to the pydantic settings, something like `poll_time_online_multiplier`?

**Comment by easybe** [comment]
I don't think it should be configurable. It should "just work" for short and long intervals.
