### ISSUE TITLE
Device's "Target Software" only set when directly assigning software

### ISSUE THREAD

**Issue by easybe** [UpstreamDataInc/goosebit#146]
I guess it should also show the software version that shall be installed when "rollout" or "latest" is selected.
Or, alternatively rename the column?

**Comment by b-rowan** [comment]
I think in the future this will be a computed field that references either a software version directly, or a rollout software version.

**Comment by tsagadar** [comment]
Had a quick look at the code. This is a regression of commit 1fb6368 in `DeviceSchema`. Target software before was looked up like this:
```
        manager = await get_update_manager(device.uuid)
        _, target_software = await manager.get_update()
```

@b-rowan not sure if using `validate_model` was a good choice in generating responses (the function name also suggests that it is rather used for deserializing requests). It reduces the flexibility and sometimes requires to load more than is being serialized.
