### ISSUE TITLE
"Home" tab redundant?

### ISSUE THREAD

**Issue by easybe** [UpstreamDataInc/goosebit#147]
At least currently, the content of the "Home" tab is almost identical to that of "Devices". Remove it (for now)?

**Comment by b-rowan** [comment]
No opposition here to removing it for now, but I think generally we should consider what the most important aspects of that page could be.  What are the things that are important to a user at first glance, things like device state, rollout status, etc.  I think eventually we will have to move that page away from the "single table" design that we use currently, and over to something more akin to a summary page.
