### ISSUE TITLE
DataTables warnings

### ISSUE THREAD

**Issue by easybe** [UpstreamDataInc/goosebit#153]
![Screenshot from 2024-10-03 09-21-47](https://github.com/user-attachments/assets/843adf18-19f6-4e03-b2c7-7cd323ce06af)

I get these annoying popups when e.g. the user session is no longer valid because of a restart of the dev server. But, I  have also seen them after having the browser in the background.

I think we should suppress them and maybe add some indicator making the user aware of communication problems with the backend.

**Comment by b-rowan** [comment]
Yeah, for sure.  I think we should try refreshing the page when this happens maybe?  Most of the time this happens it is because of an invalid session...
