### ISSUE TITLE
Progress no longer updated

### ISSUE THREAD

**Issue by easybe** [UpstreamDataInc/goosebit#171]
This seems to be a regression introduced with #167.

**Comment by b-rowan** [comment]
Maybe here?

https://github.com/UpstreamDataInc/goosebit/pull/167/commits/6e2356c6c926f16d537ef15e872f037077438087

**Comment by tsagadar** [comment]
@easybe you are sure that this was not already fixed?

**Comment by easybe** [comment]
It is not working. You can easily see that by forcing an update on our instance. I updated it yesterday.

**Comment by tsagadar** [comment]
Check once more based on current state of #177: progress updates are working.

There is an issue with accessing the logs - but this is an infrastructure issue with WebSockets on our side. So closing this ticket.

**Comment by easybe** [comment]
OK, there seems to be an (compatibility) issue with our new Scarthgap-based image. Will need to investigate some more. Sorry for waisting your time.
