### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by embetrix** [UpstreamDataInc/goosebit#31]
Is a docker (docker compose) support planned ?

**Comment by embetrix** [comment]
okay thanks, have nice holidays

**Comment by b-rowan** [comment]
Do you guys have a specific way we would want to do this?  I think my main concern here is handling the database properly, we have to make sure that alternate DB backends (like Postgres) are supported.

My ideal scenario is that this project just gets a dockerfile, and then end users could make their own docker compose to handle DB and composing with anything else they want (such as grafana/prometheus).

**Comment by easybe** [comment]
The Docker Compose file(s) in this repo would only serve as example. However, the Dockerfile should be used by CI to build and push an image to a registry.

**Comment by b-rowan** [comment]
Technically I think the request from this issue has been completed.   Docker support is done, and Docker compose is WIP as an example.

Docker image is up on docker hub at https://hub.docker.com/r/upstreamdata/goosebit

**Comment by easybe** [comment]
> Technically I think the request from this issue has been completed. Docker support is done, and Docker compose is WIP as an example.
> 
> Docker image is up on docker hub at https://hub.docker.com/r/upstreamdata/goosebit

Correct. If you could push another release I‘d be happy to finish the PR.

**Comment by b-rowan** [comment]
> Correct. If you could push another release I‘d be happy to finish the PR.

Absolutely.  Just a new release whenever to trigger the existing build?
