### ISSUE TITLE
Social preview and tagline

### ISSUE THREAD

**Issue by b-rowan** [UpstreamDataInc/goosebit#45]
Was going through the settings for the project, and noticed we didn't have a social preview yet, so I put something together quick with the logo, and a tagline `"Remote updates, simplified."`  Just curious if there are any better ideas or comments on this one before I upload it.

![goosebit-social](https://github.com/user-attachments/assets/2452ddce-d361-4987-9b5c-4a40faccc1a7)

**Comment by tsagadar** [comment]
LGTM. To deliver the promise of the tagline we will have to improve the documentation as well, explaining the required steps to get it up-and-running with a device running SWUpdate.
