### ISSUE TITLE
Chip in logo is missing pins

### ISSUE THREAD

**Issue by easybe** [UpstreamDataInc/goosebit#53]
IMHO the logo should look more like this:

![goosebit-logo](https://github.com/user-attachments/assets/bf0829b0-7d56-440c-9ff3-b9fbddf704d2)

I tried to edit the SVG with Inkscape but failed to get it exact due to skill issues. The original author would probably do a better job...

**Comment by b-rowan** [comment]
I'll see if I can fix it.

**Comment by b-rowan** [comment]
Making  PR for it now.

**Comment by easybe** [comment]
I resized the goose as the area around the head seemed a little weird to me. But, I'll let you decide.

**Comment by b-rowan** [comment]
It seems fine to me, I could maybe redesign it to make 100% sure its consistent, but its pretty good IMO.

**Comment by easybe** [comment]
@b-rowan the Social preview image needs to be updated as well.

**Comment by b-rowan** [comment]
> @b-rowan the Social preview image needs to be updated as well.

Done.
