### ISSUE TITLE
Add postgres support

### ISSUE THREAD

**Issue by easybe** [UpstreamDataInc/goosebit#54]

**Comment by b-rowan** [comment]
I think this is a good reference for how to do this, I think we want a `goosebit[postgres]` extra, which would allow people to install with the relevant dependencies - https://python-poetry.org/docs/pyproject/#extras

Regarding DB, tortoise just needs the `tortoise-orm[asyncpg]` extra, I think thats all that would be required.  Would be easy enough to just parse the URI and confirm the schema is valid.

**Comment by easybe** [comment]
The solution in #52 is not good enough?

**Comment by b-rowan** [comment]
> The solution in #52 is not good enough? It works for me…

That's basically what I'm saying to do, except move it to an extra, so if you want Postgres you just install with the `postgres` extra.  gooseBit is up on pip so I figure this is a good convention, in case we want to support other DBs in the future.

**Comment by easybe** [comment]
OK, I can do that. However, I don’t want to have multiple Docker images (at this point) so there I will install the extra as well.
