### ISSUE TITLE
Search engine optimization (SEO)

### ISSUE THREAD

**Issue by easybe** [UpstreamDataInc/goosebit#56]
When I google “goosebit”, our fork shows up and not the main repo, not even when I search for “goosebit github”. Any idea why that could be?

Also, https://upstreamdata.com/open-source-projects/goosebit/ shows up at the top, which looks very unfinished…

**Comment by easybe** [comment]
For GitHub, I suggest the following labels (from looking at similar projects):

- hawkbit
- swupdate
- ddi
- iot
- internet-of-things
- software-provisioning
- ota
- embedded
- linux

**Comment by b-rowan** [comment]
Good call.  I'll see what I can figure out here.

**Comment by b-rowan** [comment]
Not sure why, but I can't get this repo to show up AT ALL on google.

**Comment by b-rowan** [comment]
Like how is this even possible?

![image](https://github.com/user-attachments/assets/16cd1543-b3ed-4b90-b5c6-271209a4cc20)

**Comment by b-rowan** [comment]
I suppose having a github pages site and either having it link to readthedocs or just hosting the documentation independently would work?
