### ISSUE TITLE
Migrate settings to pydantic

### ISSUE THREAD

**Issue by b-rowan** [UpstreamDataInc/goosebit#67]
Do we want to try using the settings built into `pydantic`?  Since this is already a dependency of FastAPI, I think it makes more sense.

https://docs.pydantic.dev/latest/concepts/pydantic_settings/

**Comment by easybe** [comment]
Fine by me, as long as the environment variables are ALL_CAPS.

**Comment by b-rowan** [comment]
> Fine by me, as long as the environment variables are ALL_CAPS.

Yep, technically theyre case insensitive, so it can do both :+1:

**Comment by b-rowan** [comment]
FYI I'm fine with merging #64 in the meantime until we can format a schema for this, this will be a bit more work than what has been done there.
