### ISSUE TITLE
Firmware vs Software

### ISSUE THREAD

**Issue by easybe** [UpstreamDataInc/goosebit#74]
Throughout gooseBit the term firmware is used, whereas the Linux counterpart, SWUpdate uses the term software. Another "problem" I see is that in the Linux world firmware is normally what is written/flashed to peripherals or chips on the board.

Would it be an option to use "software" instead?

**Comment by b-rowan** [comment]
> Throughout gooseBit the term firmware is used, whereas the Linux counterpart, SWUpdate uses the term software. Another "problem" I see is that in the Linux world firmware is normally what is written/flashed to peripherals or chips on the board.
> 
> Would it be an option to use "software" instead?

No opposition, I'm just very used to anything flashed onto an embedded device being called "firmware", but that might be avery niche viewpoint.

**Comment by easybe** [comment]
OK. So maybe achieve some stability first? Preferably have some tests. Then do a big find & replace?

**Comment by b-rowan** [comment]
> OK. So maybe achieve some stability first? Preferably have some tests. Then do a big find & replace?

Sounds good.  Are we going to aim for 100% test coverage of the project on this note?

**Comment by tsagadar** [comment]
100% test coverage IMHO rarely makes sense. I'd focus on the DDI parts to have this covered as much as possible - here things could go wrong and in the worst case brick devices (or not detecting, that a new software bricks them).

On the UI side it is annoying to have bugs, but not much harm done.
