### ISSUE TITLE
Introduce GitHub Action to run `pre-commit` for pull requests

### ISSUE THREAD

**Issue by easybe** [UpstreamDataInc/goosebit#80]
https://github.com/pre-commit/action/blob/main/README.md

I suggest introducing a workflow file named `qa.yml`.

**Comment by b-rowan** [comment]
Apparently that is not really supported anymore, but they recommend pre-commit.ci, so I have installed that.  I tested it by deliberately pushing unformatted code to #82, and it appears to have fixed it, as well as failed checks for some other files.  See 0b4ae305e600545d42d843253b943fd2fb2c83c9.
